import styles from "./Ascii.module.css";

type Props = {
  className?: string;
};

const CountBasie = ({ className }: Props) => {
  const asciiArt = String.raw`                                                                                                                                                                                                                                                                                                                                                                      ....................:::::::::::::::;;;;;;;
                                                                                                                                                                                                                                                                                                                                                                    .....................:.:::::::::::::::;;;;;;
                                                                                                                                                                                                                                                                                                                                                                 ... ......................::::::::::::::::;;;;;
                                                                                                                                                                                                                                                                                                                                                                 .  ........................:.::::::::::::::;;;;
                                                                                                 .:;;++xxxxxxxxxxxxx+++:.                                                                                                                                                                                                                                         ............................:::::::::::::::;:;
                                                                                            .;+xxXXXXXXXXXXXXXXXXXXXXXXXXXxx+;.                                                                                                                                                                                                                                  ................................:::::::::::::::
                                                                                        :;+xXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxx;:                                                                                                                                                                                                                             ..................................:::::::::::::
                                                                                     :;xxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxx+;.                                                                                                                                                                                                                           .... ..........................:::::::::::::
                                                                                 .;+xXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxXXXxxx+x+;.                                                                                                                                                                                                                       . ...............................:::::::::::
                                                                               :+xXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxxxxxxxx+x++++;                                                                                                                                                                                                                     .. .... ..........................::::::::::
                                                                            .;xXXXXXXXXXXXXXXXXXXXXXXxxxxXXXXXXXXXXXXXXXXxxxxxxxxxx+++++++++;;;;;:                                                                                                                                                                                                                    ... ..............................::::::::
                                                                          .;xxXXXXXXXXXXXXXXXXXXXXXXXxxxxxxxxxxxxxxxxxxxxxxxxxxx++++;;;;;;;;;;;::;;:                                                                                                                                                                                                                  .. ................................:::::::
                                                                        .;xXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxxxxxxxxxxxxxxxxxxx+++++++;;;;;;;::::::::::::                                                                                                                                                                                                                  .. .................................:::::
                                                                       :+XXXXXXXXXXXXXXXXXXXXXXXXXXxxxxxx++++++++++++++++++++++;;;;;;;::::::::.........                                                                                                                                                                                                               . ...................................:.:::
                                                                     .;xXXXXXXXXXXXXXXXXXXXXXXXXXxxxxxx++++++++++;;;;;;;;;;;;;;;;;;::::::::::............                                                                                                                                                                                                               . . ................................:..:
                                                                    :+xXXXXXXXXXXXXXXXXXXXXXXXXXxxxxx++++++;;;;;;;;;;;;;;;;;;;;;:::;;:::::::::............                                                                                                                                                                                                         .       .. ...............................::.
                                                                  .;xXXXXXXXXXXXXXXXXXXXXXXXXXXxxxx++++;;;;;;;;;;;;;;:::;:::::::::::::::::::::..........                                                                                                                                                                                                                    ...................................:
                                                                 :+XXXXXXXXXXXXXXXXXXXXXXXXXXXxxxx++++;;;;;;;;;;;;;;:::::::::::::::::::::::::::........                                                                                                                                                                                                                   . ....................................
                                                                :xXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxx++;;;;;;;;;;;;;;;;;:;:::::::::::::::::::::::........                                                                                                                                                                                                                  . .   .  ...............................
                                                               :+XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxx++;;;;;;;;;;;;;;;;;::::::::::::.:.........::::.......                                                                                                                                                                                                                     .    . ............................:
                                                              .+XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxx++++;;;;;;;;;;;;;;;;;;;:::::::::............:::::......                                                                                                                                                                                                                   .   .. ..............................
                                                              ;xXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxxx++++++;;;;;;;;;;;;;;;;;;::::::::::...........:::::.....                                                                                                                                                                                                                    ...................................
                                                             .xXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxxxx++++++;;;;;;;;;;;;;;;;;;;:::::::::::.......:::::::.....                                                                                                                                                                                                                       .  ............................
                                                             :xXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxxx+++++++++;;;;;;;;;;;;;;;;;;::::::::::......::::::::.....                                                                                                                                                                                                                   .  .  ............................
                                                             ;XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxxx++++++++++;;;;;;;;;;;;;;;;;:::::::........:::::::......                                                                                                                                                                                                                 . .. ..............................
                                                             +XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxxxxx++++++++++;;;;;;;;;;;;;;;;::::::::.....::::::........                                                                                                                                                                                                               . . .................................
                                                            .xXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxxxxxxxxx++++++;;;;;;;;;;;;;;;;;;:::::::......::..........                                                                                                                                                                          .           . .                     .. ...................................
                                                            ;xXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxxxxxxx+++++++;;;;;;;;;;;;;;;;::::::::...................                                                                                                                                                                                         .          .    .   .... .................................
                                                            +XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxxxx+++++++;;;;;;;;;;;;;;;;;::::::......................                                                                                                                                                                     .     . .      .  .              ...........................................
                                                            +XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxx+++++;;;;;;;;;;;::::::::::::....................  .                                                                                                                            .            .                .                 .  . ..    . .. ..    ...  ..........................................
                                                           .xXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxx++++;;;;;;;;;;;;:::;:::::::::::..:::............    .                                                                                                                 .                                              . .            . ....  . .  .. .. .............................................
                                                            xXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxxxx++++;;;;;;;;;;;;;++++++++++++++;;;;;;;;::::.............                                                                                                                     .    .                             .             . .    . ..   .  .... ................................................
                                                            +XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxxx++++++;;;++++;;++++x+++++xxxxxxxxxxx+++++;;;::::...........                                                                                                                 .  .                                  . ..               ..           . .................................................
                                                            +XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxxxx+++++++++++++xx+xxx++;;::::;;++xxxXxxxx+++++;;;::;::::::::....                                                                                                         . .     .                                          .   . . . .... . . . .   .. .. ............................................
                                                            ;XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxxxxx++++++++xxxxxxxx++;;;::::::::;;;+xxxxx++xx++++;;;;;;;;;;++;;:.                                                                                                    .   . . .         .                   .      .   .. . .   ..  ..... .. .  ........  . ............................................
                                                            ;XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxxxxxxx++++++++xxxXxxxx+++;;;;++++++xx++++xxxxxxx++++++++++++xxxxxx+:                                                                                                                                                       . ...  ... .... ... ..  .  .. .................................................
                                                            .xXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxxxxxx+++++++xxXXxxxxx++++x+++;;:;;;;;xXxxxxxxxx++++++++++xxxxx+;::.                                                                                                                  . .                        .             .  .  . ..     ....... . ... ..............................................
                                                             ;XXXXXXXXXXx++;;;;xXXXXXXXXXXXXXXXXXXXXxxxxxxx+++++++xxxxxxxxxxxxxxxxxxxXXXXXxx++xxxxxxx+++;;++++xxxxxxxxx+:.                                                                                                                                             .   .        ..  . ..... ... ... ....  .. ...............................................
                                                             :xXXXXXXXxxXXXXXXx;:;xXXXXXXXXXXXXXXXXXxxxxxxx+++++++xxxxxxXXxxxXXXXX$$$X+Xx;;+XXxxXXxx++;;:;;:;xxxx+;;++:..:                                                                                                                 .                                   ..    . . .   ....... .... ..  ..................................................
                                                             .+XXXXXX++xXXXXXXXX+;.+XXXXXXXXXXXXXXXXxxxxxxxx+++++++++xxXXXXXXX$$$X$X$$Xx:..:+xXxx+++++;;::: .x++xX+xXXxXx;                                                                                                                  .                                    .     .  .    ..... .... .   ..................................................
                                                              +XXXXXx;;+xXXXXXXXXx+;xXXXXXXXXXXXXXXXxxxxxxxxxxxx++++++xxXXxXX$XXxxxxxx+;:..;+++xx+;;;;;;::.. :xxXXXXXX;xX+:.                                                                                                                .                             .      .      .    ...... .     .  . .................................................
                                                              .xXXXX;;:;+x+xXXXXXXx++xXXXXXXXXXXXXXxxxxxxxxxx++++++++;++++xxxxXxxx+++;:;;++++++++;;;;;;;::... ;+x+XXX;;::;.                                                                                                               .                                   .   .   .   ..  . .. ..         ...... ...........................................
                                                               ;XXXX;::++x++;xXXXXXxxXXXXXXX$XXXXXXxxxxxxxxxxx+++++;;;;;;+++++xxxxxxxx+++++++++;;:::::::::::.. :++++;:::.                                                                                                               .                                           .    ..   .     .         .. ...............................................
                                                               :xXXX;..;+++;;+xXXXXxXXXXXXXXX$XXXXXXxxxxxxxxxx+x++++;;;:;;;;;;+++++xxx++++++;;:::::::::::::::.:..+xxxxx;                                                                                                                                                                 ..   .    .            ................................................
                                                               .+XXX+..;++;:;xXXXXXXXXXXXXXXX$$$XXXXXXXxxxxxxx+++++++;;;;::::::::;;;;;;;;;;::......:::::::::::::. ;+++:                                                                                                                                                        .    .. . . .   .  .                .............................................
                                                                ;xXXX:.;++.:;xXXXXXXXXXxxXXXX$$XXXXXXXXxxxxxxx+++++++++;;;;::::::.::::::::.:........::::;;:::::::...::                                                                                                                                                             .. . .                            ...........................................
                                                                :XXXX+.:+;.:;;xXXXXXXX+xXXXXXXXXXXXXXXXxxxxxxxx++++++++++;;;;:::...................::;:;;;;;;:::.::. .                                                                                                                                                               .   . .                          ...... ..  ........ ......................
                                                                ;XXXXx:.++...:;;+XXXXXxxXXXXXXXXXXXXXxxxxxxxxxx++++++++++++;;;:::..............:::;;;;;:::;;;;:::...                                                                                                                                                                     . .  .     . . . .        . ...... . ... ..............................
                                                                +XXXXXx:.;;....;xXXXXXXXXXXXXXXXXXXXXXxxxxxxxxx+++++++++++++;;;:::........:.:::::;++;;;::::::::::. ..                                                                                                                                                                   .. . ..     . . ..           . .............. ..........................
                                                               .xXXXXXX+:.:;;;;;;+xXXXXXXXXXXXXXXXXXXXxxxxxxxxx++++++++++++++;;;;::......:::::;;;xx++;:.......:;::..::.                                                                                                                                                                       .   . ..      .    .  ................. .   ......................
                                                               .xXXXXXXXx:..:+x++:..:+XXXXXXXXXXXXXXXXXxxxxxxxx++++++++++++++++;;;::::::::::;;;;+XXx+++;;++++++++;;;;;:..                                                                                                                                                                                          .    .   ... .....  . .......................
                                                               :xXXXXXXXXX+;.;x++;;:;+xXXXXXXXXXXXXXXXXxxxxxxxxx+++++++++++++++;;;;;::::::;;;;::+XXXxxxXX$$$$XXxxx++++;..                                                                                                                                                                    .         .   ...             . ....... ...........................
                                                               .xXXXXXXXXXXXx++++;;;+;+XXXXXXXXXXXXXXXXxxxxxxxxxx++++++++++++++++;;;;;::;;;;;:...xXXXXXXXX$$$$$$XXxxx+;::                                                                                                                                                                               ..                 ..  .     ...........................
                                                                +XXXXXXXXXXXXXXxxxx++;+XXXXXXXXXXXXXXXXxxxxxxxxxx+++++++++++++++++++;;;;;;;;::.....:::::::;x$$$$XX;.:;;;:                                                                                                                                                               . .   ..   . .    .          .  .    .  ..  .  .........................
                                                                :XXXXXXXXXXXXXXXXXXxxxXXXXXXXXXXXXXXXXXXXxxxxxxxxx+++++++++++++++++++;;;;;;:::......:::::;++xXxx;;. .:;;:                                                                                                                                                                    .    .. .                   ...     . ...... ......................
                                                            .;;+xXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxxxxxx+++++++++++++++++++;;;;;::::::::::::;+xxXxx+xxx+: .;;.                                                                                                                                                           .        .. . .   . ...  ..     .            ...............................
                                                          .+xXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxxxxxxx+++++x++++++x++++++;;;;;;;;;;;;;;+xxxXxxxxx+xxxxx:;;                                                                                                                                                                   .               . .         . . ..    .. ..... ......................
                                                         .+xxx++xxXXXXXXXXXXxxXxxXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxxxxx++xx++xx+xxx+++++++++;+++++++x+xxxXXXXxxXxx+xXXxXx;:                                                                                                                                                                          . .   .                   .    .  .... .....................::
                                                        .+x+::.....:xxxxXXXXXxxx+xXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxxx+xxx+++xxxxx++x++++++++++xxxxxxxXXXXxXX+xx+++;+xXxx+.                                                                                                                                                                           .  .  .   .          .         .  ........................:::
                                                       .+x+;::...... .::;+XXXXXxx+xXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxxxxx+x+xxxxxxxxx++++++++xXXXXXXxXXXXxxxx++++;:;;+xXx;                                                                                                                                                                                    .            .  . ..  ..  ......................::..:
                                                      .+x+;:......      ...:xXXXXxxxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxxxxxxxxxxxxxxx+++++++xXXXXXXXXXXXxxxx+xxxxxxxx++xx.                                                                                                                                                                                                    .   . .. ....  ................:.....
                                                      +++;::....    ... ..   .;xXXxxxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxxxxxxxxxxxxx++++x+xxXX$$$$$$XXXXXXXXXXXXXXXXXXxx+.                                                                                                                                                                                          .  .  . ...  . . .  ...................:.:.....
                                                     ;xx+;:.....     .....      .+XXxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxxxxxxxxxxxxxxx++xxxxx+xxxxxxxxxXXXXXXXXX$XXXxXx;                                                                                                                                                                                                      .     .  ................:::::......
                                                    ;xx+;::....         ......     ;XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxxxxxxxxxxxxxxxxx++++;+++;::;;::;:;;:;;;;.  :xx+.                                                                                                                                                                                                               . ............:::::......::
                                                  .++++;:.....          .........    +XXX$XXXXXXXXXXXXXXXXXXXXXXXXXxxxxxxxxxxxxxxxxx++++++++++x+++++;..::;:       ;++                                                                                                                                                                                                              . .............::::::....:::;
                                                 .;;;;;;:...             .   .....   .;xXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxxxxxxxxxxxxxx++++++;+++xxx+++++;;;;;::.. :+x.                                                                                                                                                                                                     .      .............:::::..:....:::;;+
                                                 :+;:::::...                   ..... .;++xXXXXXXXXXXXXXXXXXXXXXXXXXXXxXXxxxxxxxxxxxx++++++++++++xxxx+++++++++++++;+:                                                                                                                                                               .                                             ............::::::::...:::;;+++
                                               .;xXXX+::...                       .....;+++xXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxxxxxxxxxxx+++++++++++xxxxxxxx+x++xxx;;;                                                                                                                                                                                                             ...........:::::::::..:::;;++++x
                                             .:::::...;+;..                        ......xxx+xxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxxxxxx++++++++++++xxxXXXXXXXXXX;::                                                                                                                                                                                                          .. ...........::::::..:::::;;;++++x+
                                           .::::::........;:                        ......xXx+++xX$XXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxxxxxxx++++++++++xxxxXXXXXXXx;;;.                                                                                                                                                                                          .               ...........::::::::::::::;;;++++++xx
                                         ..::............   ::                       ......+XXx+++xXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxxxxxxx+++++++++++xxxxxxxxx+;;;:                                                                                                                                                                                       .                 ...........:::::::::::::::;;++++++xxxx
                                       .................      .:                       .....+XXx++++xXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxxxxxx+++++++++++++++++;;::;.                                                                                                                                                                                          .             ..........:::::::::::::::;;+++++++xxxxx
                                     ...............            .:                      .....;xXXx++++xXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxxxxxxxx++++++++++;;;;;;:::                                                                                                                                                                                     .       .  . .   ...........::::::::::::::;;;+++++++xxxxxxx
                                   ...............                :.                       ....xXXx+++++xXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxxxxxxxx+++++++++++++++;:                                                                                                                                                                                     .        .  . ...........:::::::::::::::;;;++++++++xxxxxxxx
                                 ................                   :.                  .  .....;XXX+++++xxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxxxxxx++++++++++++++.                            .                                                                                                                                                              .  .. ...........:::::::::::::::;;;++++++++x+xxxxxxxx
                               .:...............                      ;.                 ........:xXXx+++xxxxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxxxxxxxxxxxx+.                                  .                                                                                                                                                        .  .. ..........:::::::::::::::;;;++++++++++++xxxxxxxx
                              .::.............                         .:               ...........;xXx+++xxxxxXX$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxxxxxxxx+.                                                                                                                                                              .                           .    ...........:::::::::::::::;;;++++++++++++++xxxxxxxx
                            .:::................                         ;.                 .........+XX++xxx++++xX$$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxXXX+.                                                                                                                                                       .                                   .   ...........::::::::::::::::;;;+++++++++++++xxx+xxxxxx
                          .::::................                           :;              . ..........:xXx++xxx+;;+xX$X$$XXXXXXX+.   .:+xxxxxxxxxxxx++:. .                                   .                                                                                                                      .                                     .........:::::::::::::::::;;;++++++++++++++xxxxxxxxxxx
                        .::::...............                                +.              .  .........+Xx++xxxxxxxxX$$$$$X$X+.                    .                                                 .                                                                                                              .                                  .........:::::::::::::::::;;;++++++++++++++++xxxxxxxxxxx
                       :::::::.............                                  ;:               . .........:xx++xxXXXXXX$$$$$XXX;.                                                            .       .    .                                                                                                    .             .                           ........::::::::::::::::;;;++++++++++++++++++x+xxxxx+x++
                     .:;::::::::...:......                                    .+.                .........:xx+++xxXXXXXXXx.  xx+:..                                                        .   .         .                                                                                          .     .  .. .    ..  ..                             .......::::::::::::::;;;;++++++++++++++++++++++xxxxxx+++
                    :;;:::::::::::::::....                                      +.           .  ............xx+++++xxxx+...:..xx+::+.                                                .            ..                                                                                         . . .   .          .    ..    .                             .......:::::::::::;;;;++++++++++xx++++++++++xxxxxxx++++
                  .:;;;;::::;;:::::.......                                       ;:              ............+x+++++++++++++;;;x+++;x.                                                    . ..            . .                                                                                  ........       .  ........                              ..........:::::::::;;;++++++x+x+xxxxxxxx+++++xxxxxxxxxx++
                 .;;;;;:;;;::::::........                                         .+.      .  .  .............++++++++++++++++;XXxx;:+                                           .       .              .  .                                                                              ...  .... .. ...     . ......... .       .                       .......::::::;;;++++xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
                :;+;;;;;;;::::::........                                            x.     .. ........ ........;++++++++++++++;X$$Xx;::                                           .            .                                                                                       ..  . . . .   . .. . . . .     ..... .                          .  .  .....::::;;;+++xxxxxxxxxxxxxxxxxxxxxxxxxxXXXXXXXXXX
               :++;;;;;;;::::::.........                                             +:       ...................++++++++++++++XXXXXXxx:                                                                                                                                                   . ... . ...  ... ..  .     .     .                               .....:::;;;+++xxxxxxxxxxxxxxxxxxxxxxXXXXXXXXXXXXXXXX
             .;+++++;;;;;::;:::.........                                              +;    . ...............     ;+++++++++++X$$$$$$Xx+                                   .                                                                                                               ..........  . .  ..  ..  .       .          .                    .....:::;;++++xxxx+++++xxxxxxxxxxxxXXXXXXXXXXXXXXXXX
            .;+++++++++;;;;;:::..........                                              ;+.       ...........       ;++++++++++X$$$$$$$Xx.                                                                                                                                                  ..           .                                                    .....:::;;;;+++;;;;;;;++++++++xxxxxxxx+++++++xxxXXX
           .;++++++++++;;;;::::.........                                                .:.    . ... .....          :+++++++++X$$$$$$$Xx;                                                                                                                                                                                                                       .......::::::::::::::::;;;;;;;;;;;;;;;;;;;;;+++x
          .++++++++++++;+;;;::..........                                                     .. ..... ...            .++++++++X$$$$$$$Xx+                                .                               .                                                                                                                                                             ..... ................::.:.........::::;;
         :++++++++xx++++++;;:::.........    ....              ....                             .........               +++++++$$$$$$$$Xx;                                                                   ........                                                                                                                  ........                                       ..........................:
        :++++++xxxxx++xx++;;:::.........   .....          ..  ..:::...       ..                  ... .                  ;++++x$$$$$XXx++:                                  .                                ....::...                                                                                                                 ..........                                                            ....
       :++++xxxxxxxxxxxx++;::::..:::.....            ..         .:;:....      ...                                        .::;x$XXxx++xx+;                                                                  ...:::::..            .                                                                                                    ...........                                                             ..
      :++x+xxxxxxxxxxxxx++;;::::..::....... .  .      .:.        .:::.....     ...  ...                                      :XXxx+++Xx;+                                                                   ..:;;;:..          ........                                                                                                   .          ...                                                     . .
     :+xxxxxxxxxxxxxxxx++;;;;::...:...............    .::..       .::::::..     ... ....                                     :Xxxxx+xXx+;.                                                                 ...:;;;:..         ..::::::::......                                                                                                                                                                  
    .;+xxxxxxxxxxxxxxxxx++;;;:.............::......    .::..       ....::::.     ..  ....                                    :XXXx+;+xx+;:                                                              .  ...:;;;:..         ..:;;;;;;;;;::::....                                                                                                                                                              
   .++xxxxxxxxxxxxxxxxxx+++;;::....  ...:::::;;;;::..   .:::..      ....::::.         ...                     :;;            .xXXxx;;+x;.;                                                            .   ...::;;;:.          ..:;;;;;;;;++;;;;;:::...                                                                                                                                                          
  .;xxxxxxxxxxxxxxxxxXxxx++;;;;:::.  .::::;;;+++++++;:....:::..      ......:..         ..                     .;+:            .xxxx+:xx; +                                                                ...::;;;:..         ..:;;;;;;;;;;;+;;;;;;;;::...                                                                                                                                                      
 .;xxxxxxxxxxxxxxxxxXXxxxx+;;;+xx+.    .:::;;;++++xx+++;;:::::::.         .....          .               ..     .;.             ;xx;:xx+.;:                                                               ...::;;;:.          .:;;++;;;+++;;;;;;;;;;;;;;;;::.                                                                                                                                                   
.;xxxxxxxxxxxxxxxxxXXxXxxxx;;:+xXX+:        ..:;++++++++++++++++;:..         ...                         .....    :.             ++;;Xx+ ;+                                                               ...::;;;:.         ..::;;+++++++++;;;;;;;;;;;;;;;;:.                                 ......                                                                                                           
;xxxxxxxxxxxxxxxxxxxXXxx++++;:;xxXXx+.          .:;++++++++xxxxxx++;::...      ..                         .:::.                   :.Xxx+.++.                                                               ..::;;;:.         ..:;;;;;;++++++++++;;;;;;;;;;;;:.                                   ....                                                                                                           
+xxxxxxxxxxxxxxxxxxxxxxxx++++++xxXXXXx+:.          .:;+++++xxxxxxx+x++++;::.........                        :;::.                  ++xx+.;;+  .                                                            ..::;;;:.         ..:;;;;;;;;;++++++++++;;;;;;;;;:.    .....                                                                                                                                         
xxxxxxxxxxxxxxxxxxXXxxxXXxx+xxxxxXXXXXXXx+;:.          :;+++xxxxxxxxxxxxxx+++;;:::.....                   .  :;;::.                 +xxXXx:x. ..                                                          ....::;::.        ...:;;;;;;;;;;;;;;;;;;;+++++;;;;:.    .;;;;:::...                                   ......                                                                                          
xxxxxxxxxxxxXxXXxXxXxxxxxxxxxxXXXXXXXXXXXxxxx+;:..         .::;++xxxxXXXXXXXxxx+++;;:::....                   ;++;:.                 +XXXx.;+  ..                                                           ...::::..       ..:;;;;;;;;;;;;;;;;;;;;;;;;;;+++:.    .:;;;;;;;;;;:::...                              .........                                                                                     
xxxxxxxxxxXXXXXXXXXxxxxxxXXXXXXXXXXXXXXXXXXXxxxxx+;;::...           .:;++xxXXXXXXXxxx++;;::.....              .+x+;:..                +XX+.:+:....                                                           ..:::::..     ...:;++++;;++;;;;;;;;;;;;;;;;;;;;:..  .:;+;;;;;;;;;;;;;;::::..                               ....::....                                                                              
xxxxxxXxxXXXxXXXXXxxxxxxxXXXXXXXXXXXXXXXXXXXXXXXxxxxxx++++;;:::....         .:;+xxXXXXXxx+++;;::...            ;xx+;:..                +X:..;;;:....                                                          ..::;;:..     .::;+++++++++++++;;;;;;;;;;;;;;;::.....:::;;;+++;;;;;;;;;;;;;:::...                             .....::::...                                                                        
xxxxXxXXXXXXXXXXXXXxxxxxxxxxxxxxxxxxxxxXXXXxxxxxxxxxxxxxxxxxxx++++;;;;::...        .:;+xXXXxx+++;;::...        :+xx+;:...               :..:;;;;:...                                                          ..::;;;:..   ..::;+++++++++++++++++;;;;;;;:::::::.........:::;;;++;;;;;;;;;;;;;;;::::..                             ....:::::....           .                                                     
xxxxxxxXXXXXXXXXXXXx;+xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx++++;:::...       .:+xXXxx+++;;::..     .;xx++::..                +x:;++;:....                                                         ...:;;;:...   .::;+++++++++++++++++++++;;;;;;;;::::............::::;;;;;;;;;;;;;;;;;;;;::::...                            ....:::::::..... ... ...                                                
xxxxxxXXXXXXXXXXXXXx:  .;xxXXXxxxxxxxxxxxxxxxxxxxxxxxXXXXXXXXXXXXXXXXxxxxx+++++;;;:....       .:+xXxx++;;::.    .+xx+;::...               .;++++;:....                                                         ..:;;;:..    ..:;+++++++++++++++++++++++++;;;;;;;;;::::::............:::;;++;;;;;;;;;;;;;;;::::...                             ...:::;;;::...   .  ..                                            
xxxxxxXXXXXXXXXXXXXXx;.   .:+xxXXXxxxxxxxxxxxxxxxxxxxXXXXXXXXxx+++;;;;;;:::::::::::::......        .;xxx++;;:..  .+x++;::...               :+x+++;:...                                                         ..::;;:..    ..:;+++++++++++++xx+x+++++++++++++;;;;;;;;:;::::::............:::;;;;;;;;;;;;;;;;;;;::::...                              ...::;;;::... .   ...  .                                   
xxxxxXXXXXXXXXXXXXXXXxx;.      .:;+xxxxxxxxx++++xxxxxxxx+;;::::::::...........  ..............         .;++++;:..  :+++;;:...               ;+xxx;:....                                                        ..::;;:..    ..:;;++++++++++xx+xxxxxx+++++++++++++;+;;;;;;;;;;:;:::::............::;;;;;;;;;;;;;;;;;:::::::...                              ...:;;;;::....                                       
xxxxxxXXXXXXXXXXXXXXXXXXx+;..         .;;++x+++++++++++;;;:::::............             .......            .;++;::. .;+;;;:..               .+xxx+;:....                                                       ..::;;:..     .::;+++++++++++xxxxxxxxx+x+xx+++++++++++++;;;;;;;;;;;::::::::............::;;;;;;;;;;;;:::;;;;;;:::.....                             ..:;++;::...                                  
XXXXXXXXXXXXXXXXXXXXXXXXXxxx++;::...          ......::::::::::............                                     :;;:. :+++;::..               .+Xxx+;:...                                                       ..::;;:..     ..:;+++++++++++xxxxxxxxxxxxxx+xx++++++++++++++++;;;;;;;;:::::::::::............::;;;;;;;;:;:::::::;;;:::::...                              ..:;;+;:                                
XxXXXXXXXXXXXXXXXXXXXXXXXXXxxxxxxx+++;;::::.......                                                                 ...;+++;;:..               ;XXXx;:....                                                      ..::;::..     ..:;;++++++++++++xxxxxxxxxxxxx++++++++++++++++++++++;;;;;;;;;::::::::::::...........::;;;;;;::::::::::::;;;:::::..                                                                 
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxxxxxxxxxxx+++++++++;;;;;;::::...................                                     :+xx+;::..               +XXx+;:....                                                     ..::;;:..     ...:;;++++++++++++xxxxxxxxxxxxxxxxx++++++++++++++++++++++;;;;;;;;:::::::::::::............::;;;;;;::::::;:;;;;;;;;;::...                                       ::..                
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxxxxxxxx++++xxxxxxxxxxxxx++x++++++;;;;;:::::..........                              .;x++;::..               xXXx+:....                                                    ...:::::..      ..:;;++++++++++++++xxxxxxxxxxxxxxx++++++++++++++++++++++++++++;;;;;;;::::::::::::::....    ....::;;;;;:::::::;::;;;;;;;;:::..                                 .:;xx+;:..          
XxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx++++++;;;::::::......... .                          .;++;:...              .XXXx;:...                                                     ..:::::..      ..:;;;+++++++++++++x+x+xxxxxxxxxx++++++++++++++++++++++++++++++++++++;;;;::::::::::::::::...       ..::;;;;;::::;;;;::;;;;;;;;::...                                  .;xxx+:..    
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx++++++;;;;;::::::::............                      .;;:..               :XXx+::...                                                   ...:::::.       ..::;;++++++++++++++x+xxxxxx+++++++++++++++++++++++++++++++++++++++++++++;;;;;;:::::::::::::::.....     ...:;;;;;;:;:;;;;;;;;;;;;;;;;::..                                  .;xXxx;
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx++++++++;;;;;;;:::::::::.............                    .::..               xXXx;:...                                                   ...::::...       ..:;;++++++++++++++++x+x+++++++++++++++++++++++++++++++++++++++++++++++++++++;;;;;;::::::::::::::::.....      ..:;;;;;;:;;;:;;;;:;;;;:;;;;;;:..                                  
XXXXXXXXXXXXXXXXXXXXXXXXxxxxxxXXXXXXXXXXXxxxxxxxxxxxxxxxxxxxxxx+++++++;;;;;;;::::::::::.........:::.::::::....                  ....               XXx+::...                                                  ...::::..        ..::;;++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++;;;;;::::::.:::.::::.....       .:;;+;;;;;:::;;;;;;;;;;;;;;;;;:..                            
XXXXXXXXXXXXXXXXXXXXXXXXx;.   .:;+xxxxXXXXXxxxxxxxxxxxxx++;;;;;;;;;;;;;:::::::::........................::::.....                ....              .XXx;:...                                                  ...::::..        ..::;;+++++++++x++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++;;;;;;::::::::.::::::......       .:;++;;;;;;;;;;;;;;;;;;;;;;;;;;:.                      
XXXXXXXXXXXXXXXXXXXXXXXXXXx;:.        ..:;+++xxx++++;;::::::::::::::::::::::::..................... .............                 ....              ;XX+;:....                                                ..:::::..        ...:;;;;;+++++++++xxx++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++;;;;;:::::::::.::..:..:....      .:+++;;;::::;;;;;;;;;;;;;;;;+;;:.                
XXXXXXXXXXXXXXXXXXXXXXXXXXXXx+;:.                     ................................                                            ....               xXx+:....                                                ..:::::..         ..:::;;;;;+;+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++;;;;;::::::::::.::.:.....       :;+++;;;;;:;;;;;;;;;;;;;;;;;;;;:.. ;:  .   
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxx+;:.                                  .... .. .......                                              ....               XX+;:...                                                ..:::::..         ...::;;;;;;;;;;+;++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++;;;::::.:..:::::........      :;+++;::;;;;;;;;;;;;;;;;;;;;;+;;:.   
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxx+;:...                                                                                           ....  .           :Xx+;:..                                                ..:::::..         ...:::;;;;;;;;;;;;;;;;+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++;;::::::...:::::::::....     .:++++;;;;;;;;;;;;;;;;;;;;;;;;;;
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxx++:::......                                               .  ..........:..:::::.:.......       ...  .+           +X+;:...                                               ..:::::..         ...:::;;;;;;;;;;;;;;;;;;;;;;;;;+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++;;;::::.:::.:::::::::....     .:+x++;;;;;;;;;;;;;;;;;;;;
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx++;::::.............                             ...:::;;;;;;++++++++xxxxxxxx++++;;;;:::..        ;X:          xx;:....                                              ..:::::.         ...::::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++;;;:::::..::::::::.:.....     .;xx++;;;;;;;;;;;;;;
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxx++;;;::::::::.........................   ...::;;++++xxxxxxxXXXXXXXXXXXXXXXXXXxxx+++;;;::..     xXx.        :X+:.....                                            ...::::..         ...::::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++;;;:::::::::::::::::.....     .;xXx+;;;;;;;;
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxx++;;;:::::::::.....................  ...:::;;;;;;+++++xxxx+++;;:..  . .:+xxXXxxx+++;;;;:..  :xXx:        ++;:....                                           ....::::..         ..::::;;;;;;;;;;;;;;;;:::::::;;;;;;;;;;;;;;;;;;++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++;;;:::::..:::::::::::....     .+XXx+;;
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxx++;::::::::::::.................    ....                               .:;+xxxx++++;;;::.  ;xXx.      .x+;....                                           ....:::..          ...::::;;;;;;;;;;;;;;:.......::;;;;;;;;;;;;;;;;;;;;;;;;++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++;;::::::::::::::::::::....    :+
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxx++;:.............:::.:::::::::..                                          ...;++++++;;;:.. :xXX;      :+;:...                                          .........           ...::::;;;;;;;;;;;;;;:........:;;;;;;;;;;;;;;;;;;;;;;;;;;;;++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++;;:::::::...:::::::::.... 
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxxx++;:...........::::::::::;;;:..                                               .::;;;;;::. :xXX+      x;:....                                        .........             ..:::::;;;;;;;;;;;;;;:.....:::;;;;;;;;;;;;;;;;;;;;;;;:;;;;;;;;;;++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++;;:::::::.:::::.:.
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxx+xxxx+;:...........::::;;;;;;;+;;:..                                                ...::::.. ;XXXx.    :+:....                                          .....               ...:::::;;;;;;;;;;;;;;::::::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;::::;;;;;;;;+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++;:::::::::::::
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxx++xxx+;:....... ...::;;+;;;;+++++;::..                                                 .....  +XXXx:    +;:...                                                              ...:::::;;;;;;;;;;;;;;;++;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;::::;;;;;;;;++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++;:::::::
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx;;++++;:......   ..::;;+++++++++++;;::...                                                     +XXXx:   :+:...                                                              ...::::::;;;;;;;;;;;+++++++;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;::::;;;;;;+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++;;:
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx+;++++;:.....    ..::;++++++++++++++;;:::........ .. .                                       .xXXXx:   +;:....                                                            ...::::::;;;;;;;;;;+++++++;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:::::;;;;;+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx+;++++;:......   ...::;;;;+++++++++++;;;:::::........................                        .+XXXx.  ;+:...                                                             ...::::::;;;;;;;;;++++++++;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:::::::::;;;;;++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxx++x++;:.....     ...:::::;;++++++++++;;;;;;;:::::::::..................                     .xXXX+  .+;:..                                                              ...:::::;;;;;;;;;++++++++;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:;:::;::::::::::;;;;+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx+++++;:..         ......:::;;;;;;;;;;;;;;;;;;;;::::::::::................                   :xXXX;  +;:....                                                            ...::::::;;;;;;;++++++++;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;::;::::::::::::::;;;;++++++++;;++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxx++++;:..         .........:::;;;;;;:::;:;;;:::::::::::::...................                +XXXx. :+:....                                                            ...:::::::;;;;;;++++++;;;;;;;;;;;;;;+;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:::;:::::::::::::::::;;;;+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx++x+;:..           ..........::::::::::::::.:::::::::::.....................              :xXXX+ .+;:...                                                            ...:::::::;;;;;;+++++;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;::::;:::::::::::::::::::::;;;+++x+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxx+;::..                  ................................................               ;xXXx. ;+::...                                                           ...:::::::;;;;+;;++;;;;;;;;;;;;;;+++;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;::::::;;:::::::::::::::::::::::::;;+++xx++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx+++;::..                     ..............................   .  . . . ....              ;xXX+ .+;:....                                                          ...::::::;;;;;;++;+++++;+++++;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;::::;:;:;;:::::::::::::::::::::::::::::;;++xxx+++++++++++++++++++++++++++++++++++++++++++++++++++++++
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx+x+;:..                         ......... ..    .                                               ......                                                         ....::::;;;;;;;;;+++++++;+++++++;+++;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:;:::::::::::::::::::::::::::::::::::::::::;;;++xxx++++++++++++++++++++++++++++++++++++++++++++++++++
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx+++;::..                             .                                   .                         ...                                                        ...::::;;;;;;;;;;++++++++++++++++;+++;;;;+;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:::::::::::::::::::::::::::::::::::::::::::::::::;;++xxx+++++++++++++++++++++++++++++++++++++++++++++
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX$XXXXXXXXXXXXXXXXXXXXXXxxx+;:....                                                                                          .                                                         ...:::;;;;;;;;;++++++++++++++++++++;+;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;::::::::::::::::::::::::::::::::::::::::::::::::::::::;;++xxxx++++++++++++++++++++++++++++++++++++++++
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxXx+;::.....                                                                                                                                                ...::;;;;;;;;+++++++++++++++++++;++;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;::::::::::::::::::::::::::::::::::::::::::::::::::::::::::;;++xxxxx++++++++++++++++++++++++++++++++++
XXXXXXXXXXXXXXXX$XXXXXXXXXXXXXXXXXXXXXXXXXXX$$XXXXXXXXXXXXXXXXXXXXXXXXXXxxx;;:::....                                                                                                                                  . .. ........:::;;+++++++;+++++++++++;+;+++++;++;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::;;;++xxxxx+++++++++++++++++++++++++++++
XXXXXXXXXXXXXXXX$$XXX$XXXXXXXXXXXXX$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx++;;::.... ..  .                                         .. .. .....                                                        ....:::::::::::::::::::::::;;+++xxxx+++++++++++++++;+;+++;;+;++++;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::;;;;;;++xXXxx++++++++++++++++++++++++
XXXXXXXXXXXXXX$$$$$$XXXXXXX$XXXXXXX$$XXXXXXXXXXXXXX$XXXXXXXXXXXXXXXXXXXXXXXXXxx++;;::.............  ....     ....    .. ..... . ....................                            ...       ....      ....::;++x+++++++++++++++++++xxxxxxXXXXxxxxxxxxxxx++++++;;;;;;;+;+;+++++++;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:;;::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::;;;;;;;;+xxXXxx+++++++++++++++++++
XXXXXXXXXXXXXXX$$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX$X$X$$$XXXXXXXXXXXXXXXXXXXXXXXXXxx+;;::............................................................ .                 .         ....    ................:;;+xxxXXXXXXxxxxxxXXXXXXXXXXXXXXXXXXXXXXXXxxxxx+++++;++++++;;;;;;;++++++++;;;;;;;;;;;;;;;;;;;;;;;;;;;:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::;:::::::;;;;;;;;;+++xXXxx++++++++++++++
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX$$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxx+;;:::..........................................................          ...            .  .....   ................::;;++xxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxx++++++++++;;;;;;;;;;++++;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::;;;;;;;;;;;++++xXXXx+++++++++
XXXXXXXXXXXXXX$X$$X$XXXX$XXXXXXXXXXXXXXXXXXXXXXXXXXXXX$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx++;::::............::::::::::::::::::..........................       ....  . ....    ..   ....               .....:::;;;++xxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxxxxxx++++++;;;;;;;;;;;;++++++++++;;;;;;;;;;;;;;;;;;::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::;;;;;;;;;;;;++++xXXXx++++
XXXXXXXXX$XXX$$X$$$$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxx+;:::::..:...::::::::::::::;;;;;:::::::.......................     .... . ........ ..   ......                         ....:;;+++xxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxxxxx++++;;;;;;;;;;;;;;;++++;++;+;;;;;;;;;;;;;;;::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::;;;;;;;;;;++++++xXXX
XXXXXXXXXXXXX$XXXX$$X$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx+;;:::::::.::::::::;;;;;;;;;;;;;;;;;::::..............:..............    ......  ..    .......                  .....             .....:::::;+xXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxxx+++++;;;;;;;;;;;;;;;;++++++;;;;;;;;;;;;::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::;;;;;;;;;;;++++++
XXXXXXXXXXX$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx+;;::::.:::::::;;;;;;;;;+++++;++;;;;:::::............:::.::.......    . ....  .      .......                    ..                         .:;+xxXXXXXXXXXXXXXXXXXXXXXXXXXXXxxx+++++++++;;;;;;;;;;;;;+++;+;;;;;;;;;;;::;::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::;;;;;;;;;;;++
XXXXXXXXXXXXX$XXXXXXXXXXXXXXXXXXXXXXXX$XXXX$$$X$XXX$$X$XX$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx+;;::::::::::;;;;;;++++++++++++++;;;::::::.........::::::::::... . ......   ..      .........                                                       .....;xXXXXXXXXXXXXXXXXXXXxxxxxxxx++++;;;;;;;;;;;;;;;;;;;;;;;;;;;;:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::;;;;;;;;;;;
XXXXXXXXXXXXX$XXXXX$XXXXXXXXX$X$$$X$$XX$XXX$$$$$$$$X$$$X$$X$X$$$$$X$XXXXXXXXXXXXXXXXXX$$$$XXX+;:::::.::::::;;;;;+;+++++++++++++;;:::::::......:..:::::::..    .......  ...   .............                                                          ..:;xXXXXXXXXXXXXXXXXXXXXXXXXXxxx+++++++;;;;;;;;;;;;;;:::::;::::::::::::::::::::::::::::::::::::;:::::::::::::::::::::::::::::::::::::::::::::::::::::::;;;;
XXXXXXXXXXXXXX$XXXXXXXXXXXXXX$$$$$$X$$$X$$X$$$$$$$$$$$$$$$$$$$$$$X$$X$XXXXXXXXXXXXXXXXXXXX$$Xx+;::::...:::::::;;:;;;;;;;;;;;++++;;::::::..:::........::... .          ...    .............                                                           ::.:;xXXXXXXXXXXXXXXXXXXXXXXXXXxxx+++++++++;;;;;;:::::......::::::::::::::::::::::::;:;;;:::::;::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
XXXXXXXXXXXXXXX$$$X$XX$$$XX$$$$$$$$$$$$$$$$X$$$$$$$$$$$$$$$$$$$$$$X$X$XXXXXXXXXXXXXXXXXXXX$$$Xx+;::.......::::.........:::::;;;;;;;:::::::....................        ..     ................                                                                  .:;+xxxXXXXXXXXXXXXXXXXXxxxxxxxx+++++;;:::;::........:::::::::::::::::::::::;;;::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
XXXXXXXXXXXX$$$$$X$XXXX$$$$$$$$$$$$$$$$$$X$$$$$$$$$$$$$$$$$XX$$$$XXXX$$$$$$XXXXXXXXXXXXXXXXXXXXx+;:..............      .....:::;;;:::::::........  .............      .      ......................                                                                      ..:;+xxXXXXXXXXXXXXXXxxxx++++++++++++;:::;;;;::::::::::::::::::::::;;::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
XXXXXXXXXX$$XXX$$XXX$$$$$$$$$$$$$XXXXX$$$$$$$$X$$$XX$$$$$$$$X$$$$XXXX$XX$$$$X$XXXXXXXXXXXXXXXXXXX+;::.........             ....:::::::.......     ..............             ............ .......  .  ..                                                                 .......;xxxxxxxxxXXXXXXxxxxxxxxx++++;;;;;;+++;;:::::::::::;:;::::::::;:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
XXX$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$XXX$$$X$$$X$X$XXXXXXXXXXXXXXXXXX+;:.........               .............       ................            ................................ ...                                                          . ....    .;+++xxxxxxxxxxxxx+++;;;;;;;+++++++;:..::::::::::;;::::;:;;::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$X$$$X$$$$$$$$$$XXXXXXXXXXXXXXXx+;......                      ....          .................             ......... .............................                                                           . .          .:;+++xxx+++++;;;+++x++++++++;:.....::;;;;;:::::;;::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
$XX$$$$$$$$X$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$X$$$X$$$$$$$$$$$$$XXXXXXXXXXXXX++:.   . ..... .                          ....................             ........................................                                                                              .++++++++xx+++++xx++x++:.......:::;:::::;:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$X$$$$X$$$$$$$$$$$$$$$$$$$XXXXXXXXXXXx;+:...........                       ...................::...            ... ... .....:::::::....................... ..                                                                          :+xx+++x++++xxxx+++++++;::........:::::::;;:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
$X$XXX$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$X$$$$$X$$$$$$$$$$$$$$$XXXXXXXXXXXxx+;;:::::.....                  ....................::::...          ... .......:::;;;;:::::.......:...............                                                                            .++;;;+++++xxxx+++++xx+;;::::........::;;::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
XXXXX$$$$$$$$$$$X$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$X$$$$$$$$$$$$$$$$$$$$$$$XXXXXXXXXXXXxx+++;;:....           .. ........:::::::.......::::::..          .... ....:::;;;;;;;:::::.:::::.:...............                            .                      .                        .;;:::;;;++++++xxxxxxx+;;;;;:::::.......::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
XX$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$XXXXXXXXXXXXxx+;;;:...         .......::::;;+++++;;::.....::;;::..         . .....::;;;+;;;;;:::::::::::::..................                 ......   ..... .                                          ;+++++++++++;;;++++xxx;:::;;;;::::::........:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$X$$$X$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$XXXXXXXXXXxx++;;:..        .....:::;;++xxXXxx+;;::...::;;++;:..         ....::;+++++;;;:::::::::::....:............... . .            .......................  .. .. ..                            .+++++++xxxx+++;;;;;+++::;+++;;;;::::::::........::::::::::::::::::::::::::::::::::::::::::::::::::::::
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$X$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$XXXXXXXXXXxx+;:..       ...::;;++xxXXXXXXXx+;:::.:::;++++;:..      ...:::;;+++++;;::::::::..::::::....................         . ..........................  ..........                          ;;++++++++xxxxx++++;;+++xxxxx++;::::;:::::::..  ....::::::::::::::::::::::::::::::::::::::::::::::::::
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$X$$X$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$XXXXXXXXXXXx+;:.......:;;++xxxXXXXXXXXXXx+;;::::;;++xx+;;:......:::;;;+++++;;;;;:;::::::::......................        ...................... ........................                       :;;;;;+++++++xxxxxxxx++++++++++;;;+++;;;::::::....  ....::::::::::::::::::::::::::::::::::::::::::::::
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$X$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$XXXXXXXXXXXXxxxx++xxxxxxxxXXXXXXX$$$$Xx++;::::;;++xx+++;;;;;;;;;;+++++++;;;;;::;;::::::::.......................................... ........... ......................                      :;;;;;;;++++++++xxxxxxx++++;;:;++xXXXXx;::::::::::..... ....:;::::::::::::::::::::::::::::::::::::::::
$$$$$$$$$$$X$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$X$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$XX$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX$$$$$$XXx++;;;;;++xxxx+++++++++++++++++;;;:;:::;;;;::;::::........................................... .. ... ...  .....................                      ;;;;;;;;;;;++++++++++xxx++++++;++xXXXXx+;;;++;;;:::::::::..  ...::::::::::::::::::::::::::::::::::::::
$$$$$$$XXX$X$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$X$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX$$$$$$XXxx++;;;++xxxxx++++++++++++++;;;;;:::::::::::::::::...........................::................      . ....... ................                      ;;;;;;;;;;;;;;++++++++++++x++++++x++++++++;;;;;;+++::::::::::... ...::::::::::::::::::::::::::::::::::
$X$XXXXXXXX$$$X$X$XXX$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX$$$$$$XXXxx+++++++xXXxx+++++++++++++;;;;::::::::::;;:::::::::.....................:::::::::::...:...... ..    .   .    .................                      ++++;+;;;;;;;;;;;+++++++++++++++xxx+++++;;;;;+++++++++++++++;:::::..  ...:::::::::::::::::::::::::::::
XXXXXXXXXXXXX$XXXXXXX$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX$$$X$$X$XXxxx++++++xxXXXXxx+++++;;;;;;;;;:::::::::::::::::::::.::::::::...........:::::;;;;;;;:::::.......... .               ............                     .;;;;;;;;;;;;;;;;;;;;++++++++++++++++++++++++++;;;;;;;;;;;+;;;++::::::...  ..::::::::::::::::::::::::::
XXXXXXXXXXXXXXXXXXX$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX$$$$$$XXXXXXx++;;++xxXXXxxxx++;;++;;;;;::::::::::::::::::::::::::::::::::..::::::::::;;++;+;;;;;:::::.............            ...........                      :;;;;;;;;;;;+;;;;;;;;;;;;;;;;;++++++++++++++;;;;;::::::::::;;;;;++;:::::::.... ..:;:::. ....:::::::::::
XXXXXXXXXXXXXXXX$X$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX$$$$$$$$$$$XXXXXXxxx+++++xXXXXxxx++;;;;;;::::...::::::::::::::::::::::::::;;;;;:::;;;;;++;;;;;;;;;;;:;::::::::.:.............................                      ;;;;;;+;;;;;;;;;;;;;;;;;;;;;;++++;+++++++++;;;;;;;;;;;;;;;+++;;;;;;;;:.:.:..:....   .::      ..::::::::
XXXXXXXXXXXXXX$$$$X$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX$$XX$$$$$XXXXXXXXXXXxxxxxXXXXXxx++;;;;;::::::::::::::::::::::::::::;;;;;;;;;;;;;++++++++++;;::::::;;;;;;;;::::::::::::.....................                     .+;;;;;;;;;++;;;;;;;;;;;;;;;;;++++;+;;;;++++++++++++xxxxxxxxxx++;;;;;;;;::::...........:;;;.      .:::::
XXXXXXXXXX$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$X$$$$$$$$$$X$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxx++;;;;;;;;;:::::;;;;;;;;;;;;;;::::;;;;;;;;;;;;++++xxxx+++++;;;:::;;;;;++;;;;;;;;;;;;;;;::::::..............                     ++++;;;;;;;;;;;;;;;;;;;;;;;;;;++++;;;;;;;;;;;;;;;;+++++++xxxXXxx++;;;;;;;+xx+;:.......::;;;++x+:.   ::::
XXXXXXXXXXXXX$$$$$X$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxxXXXXXXXXXXXXXXXXXXXXXXXXXXXx+;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;+++;;;;;;;;;;+++++++++++;;;;;;;;;;;;;++++++++;;;:;;++++;;;::::::...........                    :xxx++++;;;;;;;;;;;;;;;;;;;+;;+;+++++;;;;;;;;;;;;;;;;;;;;+;+;++xXXxx+++;;;++XXx;:.........::;;;+++x+:+;::
$XXXXX$XXX$XX$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$XXX$XX$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxxxxxXXXXXXXXXXXXXXXXXXXXXXXx+;:::;;;;++++++++++++++++++++++xx++++;;;;;;;+++++++++;;::::::;;;;+++++xxxxxxx+;:::;++++;::::::............                    +xxxxxx+++++;++;;;;;;+;;;;;+;;+++++++++;;;;;;;;;;;;;:::;;;;+;;;+;;;;+xxx+++++xx;::.:::......:::;;++..   :
XXXXXX$XX$XXX$$$XXXX$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$X$$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxxxxxxxxXXXXXXXXXXXXXXXXXXXxx++++++xxxxxxxxxxxxxxxxxxxxxx+++;;;+;++++++++++++;;:::::::;;;+++++++++++xx++++++:;;;++;;;:;;;;;:.........                   :XXXXXXXXxxxx++++++++;+++++++;++++++;;++++;;++++++++;;;;;;;;;;;;;;;;:;;;++xx++xxxxx++;;:.. ......::::.:...
XXXXXXX$XXXX$$$X$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$XX$XXXX$XXXXXXXXXXXXXXXXXXXXXXXXX$$X$$$$XXXX$$$XXXXXX$X$XXXXXXXXXXXXXXXXxxxxxxxxxxxxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxx++++;+++++++++++;;;;;;;::::;;;++++++;;;:::::;xXx+XX+;+++xxx+;++xxx+::.........                  x$X$$XXXXXXXxxxxxxxx++++++++;;+++;;;++;;;;+;xxxxxxxxxxxxxxxx+++;:::.....:;;+xxxxxxxxxxxxxxxxx+++;:::::...:
$$XXXX$XX$$X$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$XXXXXXXXXXXXXXXXXXXXXXXXX$$$$$$$$$$$$$$$$$$$$$$$$$XXXXX$XXXXXXXXXXXXXXXXXXXxxxxxxxxxxxXXXxxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxxxxxxx+++;;;;;;;;;++++++++;;;;::::::;xxx+xxXxx+;+;x++;+++;xx+:...........               :$$$$$$$$XXXXXXXXXxxxxxx+xx++++++;;;;;;;;;;++++xxXXXXxxxxxxxxxxxx+++;;;::::;;;:;+XXXXXxXXXXXXXxXX+++:  ...:
$$$XXX$$X$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$XXXXXXXXXXXXXXXXXXX$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$XXX$XXXXXXXXXXXXXXXXXXXXXXXXxxxxxxxXX$XxxxxxxxxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxx+;::;;++xxxxx++;;::::;;;:::XX+++++xxX+;+;;+;x++X;+++........... ........       xX$$$$$$$$$$$$XXXXXXXXXxxxxxxx++++++++++;;;;;;;++++xxxxxxxxxxxxxxxxx++++++++;;:.;;;..:;+XXXXXXXXXXXXXXXX+::
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$XXXXXXXXXXXXXX$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$XXXX$XXXXXXXXXXXXXXXXXXXXXXXXXXxxxxXX$Xxxxxxxxxxxx;::;++xxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX$XXXXXXXXXXXXXXXXxxXxx++++++++++++XX$XXXX++$Xx++x+ xx;;;.+:  ......  .:x;  ......    .;+XXXXXX$$X$$$X$XXXXXXXXXxxxxxxxxx+xxxxxx+++;;;;++;;++X$$$$XXXxxxxxxxxxx++x+++;;;:;:    ..+XXX$XXXXXXXXX;..
X$$$$$$$$$$$$$XXX$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$XX$$XXXXXXXXXXXXXX$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxXX$$$Xxxxxxxxxxx+;.  .    .:;+xxxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxXXXX+:::.xXxx;.......:..;xxxxxx: ......  .+++xxxXXXXXXXXXXXXXXXXXXXXXXxxxxxxxxxxxXXXxxxx+++;;+;++++xX$$$$$$$$XXXXXXXxxxxx+++;::......;XXXXXXXXXXXXXx;.
$$XXXX$$$$X$$$XXX$$$X$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$X$XXXXXXXXXXXXX$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxXX$$$$Xxxxxxxxxxx++.               .:;+xxxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxx+;;++++++xxxxXX$$$$$$$$$XX$Xxxx++;;;;:::;;;;;;:: +xx+x++;    .....;++++xxxxxxXXXXXXXXXXXXXXXxXxxxxXxxxxxxxxXXXXXxxx+++;+;;;;;;;+x$$$$$$$$$$$$$$XXXxx++++;;;:::+xxxxxxxXxXXXXXXX
XXXXXXXXXXXXXXXX$X$XX$$X$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$XXXXXXXXXXXXXX$$$$$$$$$$$$$$$$$$$X$$$$$$$$$$$X$$$$$$$$$$$$X$XXXXXXXXXXXXXXXXXXXXXXXXXXXX$$$$$Xxxxxxxxxxxx+:....                    .:;++xxXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxx++++;+;;xXXXxxxxXX$$$XXXXXXXXXXXXXXXXX+  .+xxXXx+        ..+++++++xxxxxxxXXXXXXXXXXXXxxxxXXXXXXxxxxxXXxxxxxxxxxx++;:::.::;;+xxxXX$XXXX$XXXXXXxxxxxxxxxxxxxxxxxxxxxXXXXXX
XXXXXXXXXXXXXXXXXXXXXXX$$XX$X$$$$$$$$$$$$$$$$$$$$$$$$$$$$XXXXXXXXXXXXXXXXXXXXXXXXXX$X$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$XXXXXX$X$XXXXXXXXXXXXXXXXXXXXXXXX$$$$$$Xxxxxxxxxxxx+:....                             .:;+xXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxx++++++++xXXXXXXXXXXXXXXXXXXXX.    ;x+;:          .+++++++++xxxxxxXXXXXXXXXXXXXXXXXXX$$$$$XxXXxXxx+xxxxxxxx+++;:::. .;;+X$xXXXXXXXXXXXXX$XXXXX$XXXXXXXXXXXXXXxxx
XXXXXXXXXXXXXXXXXXXXXXXXXX$$$$$XX$$$$$$$$$$$$$$$$$$$$XXXXXXXXXXXXXXXXXXXXXXXXXXXX$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$XXXXX$XXXXXXXXXXXXXXXXXXXXXXXX$$$$$$XXxxxxxxxxxxx;::::.                                    .;xxxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX;                    ;+++++++++++++xxxXXXXXXXXXXX$XXXXXXXXX$$x+++xx$$$$XXxxxxxxx++++::.  .:::+XXXXXXXXXXXXXXXXXXxxxxxxxXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX$XX$$$$$$$$$$$$$$$XXXXXXXXXXXXXXXXXXXXXXXX$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$X$$$$XXXXXXXXXXXXXXXXXXXXXXXXXXX$$$$$X$$Xxxxxxxxxxxx+;++:.                                          ..:;+xxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx;;+++++;:.           ++++++++++++++++xxxxXXXXXXXXXXX$$$XXXXXXx++;;+XXX$$$$$XXxxxxx+++++:. ...   :. .XXXXXXxXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX$X$$$X$$XXXXXXXXXXXX$$$$$$$$$XX$$$$XXX$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX$$XX$$XXXXXXXxxxxxxxxxx:                                              ..:;+xxxxxxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxx++++xxxxxxxxx+;:.:+++++++++++++++x+xxxxxxXXXXXXXXXXX$XXXXXx+;;;+:      .:;+x+++;;;;::..  .... .    ::...:XXXXXXXXXXXXXXXXxxxxxxx
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX$$$$$$$XXXXXXXXX$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX$XXXXXXXXXXxxxx+;++:                                                 ..:;;xxxxxxxxxxxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX;   ...::::;+xxxxxxx++;;;+++++++++++++++++xxxxxxxxXXXXXXXXXXXXXXXX+;::::;;..::;;++:                          .xxXXXXXXXXXXXXXx+XXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX$$$XXXXXXXXX$$$$$$$$$$$$$$$$$$$$$$$$$$X$$$$$$$$$$$$$$$$$$$$$$$$$$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX$XXXXXXXXXXXXX;::+;..                                                    .::;+xxxxxxxxxx++xxxXXXXXXXXXXXXXXXXXXXXXx.       ....:::;;;;;++;;;;;++++++++++++++x+xxxxxxxxxxx+:.         .+++:.....      .;;++:                         ....      XXXX$$XXXXxx
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX$$$$$$$$$$$$$$$$$$$$$$$$$$$$$X$$$$$$$$$$$$$$$$$$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx+;..::.....                                                     ..:;+xxxxxxx++++++++++++++xxXXXXXXXXx+:..          ...:;;;;;;;;;;+++++++++++++++++xxxxxxxxxxxxx++;.          .::..:.... ::::::;;+;.                              xXXXXXXXXXXx+
XXXXXXXXXXXXXXXXXXXXXx++;;:.;+xXXXXXXX$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxXX+:    ..........                                                      .:;+xxxxx+++++++++++;;;;;;;;;;++;;;;;;:.           .:;;;;;;;;;;+++++++++++++++++xxxxxxxxx+xxx+++;;:.          .;.....::..::;::;;;:.                          .+xxxxxxXxXXX$
XXXXXXXXXXXXXXXXxx;:....::;+xxXXXXXX$X$$$$$$$XX$$$$X$$$$$$$$$$XXX$XXXX$XXXXXXXXXXXXXXXXXXXX$XX$X$$$$$$$$$$$$$$$XX$$$$$$$$$$$$$$$$XX$XXXXXXXXXXXXXXXXXXXXXXXXx+:...   ..............                                                    ..:;+x+++++++++++;;;;;;;+;+;;;;;;;++;;;:.        .:;;;;;;;;;++++++++++++++++++xxxxxxxxxxx++++x++++;:.           .. ;.....::::::;;;+;                               xXXXXX
XXXXXXXXXXXXx+;:....::;;++xxXXXXXXX$$$$$$$$$$$XXX$$$$$$$$$$$$X$XXXXXXXXXXXXXXXXXXXXX$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$XXXXX$XXxXX+;;::..    ..................                                                  .:;++++++++++;;;;;;;;;;;;;;;;;;;;+;+;;;;:...:::::::;;;;;;;+++++++++++++++x+++xxxxxx+xx++xx+++++++++;..          .:::..;.....;:::;;:;;.                          :;++++
xxXXXXXXx+;:....:::;;+xxxXXXXXXXXXX$$$$$$$$$$$$X$X$$XXX$$XXXXXXXXXXXXXXXXXXXXXXX$$XX$$$$$$$$$$$$$$$$$$$$$$$$XX$XX$$$$X$$$$$X$$$$$$XXXXX$X$$$$$$$$$$$$$Xx+;:........    ......................                                                .:;++++++++;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:::::::;;;;++++++++++++++++++++xxxx++++++++++++++++++++;;::           .:+.....;..:::;;;;;;:.                            
;++++;:......:;;++xxxXXXXXXXXXXXXXX$$$$X$$$$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX$$$$$$$$$$$$$$$$$$$$$$$$$$XXX$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX+:.........    ...::..   .......................................................... .....:;++++++;;;;;;;;;;;;;;;;;;;;;;;;;;;;;+;;;;;;;;;;;;+++++++++++++++++++++++x+x++++++++++++++++++++++++:.           .:::;. ...;:::::;+;+;.                        
::::.....::;;+xxxXXXXXXXXXXXXXXXXXX$XXXx++xxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX$$$$$$$$$$$$$$$$$$$$XX$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX;.:::.....     ..:::..    ................................................................::;++++++;;;;;;;;;;;;;;;;;;;;;;;;;;;;+;+++;;;;;;;++++++++++++++++++++++++++++++++;++++++++++++++++++++;.            ::....;...::;:::;;;::                     
:......:;++xxxxxXXXXXXXXXXXXXXXXXXx+:..:;+xXXXXXXXXXXXXX$$$$XXXXXXXXXXXXXXXXXXX$$X$$$$X$$$$$$XX$$X$XXXX$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX$$Xx+..:::::...   ..:;;:..    ... ....................:::::::::::::::::::::::::::::::::::::::::::::;+++++;;;;;;;;;;;;;;;;;;;;;;;;;;+++++++++++++++++++++++++++++++++++++++++++++++;;+++++++++++++++++++;:.            .:+.....;..:::;+;;;;.                 
...::;;+xxxxxxXXXXXXXXXXXXXXXXXx;:..::;;;;+xXXXX$$X$$$$$$$$$$$XXXXXXXXXXXXXXXXXXXXXXXXXXXX$XXX$X$XX$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX$$$X+  ..::::::...:;;;;;:.........       ................:::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;+++++;;;;;;;;;;;;;;;;;;;;;;;;;+++++++++++++++++++++++++++++++++++++++++;++++++++++++++++++++++++++++;:.           .....;.....:;:::;;:;:.             
;;++xxxxxxxXXXXXXXXXXXXXXXxx+::.............:;+xxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX$X$$$Xx.   ..:::::;++;;;;::;;;;+;..        ..   .............:;;;+++++++++++++++++++++++++++++++++++++++++++++++;;;;;;;;;;;;;;;;;;;;;;;;;;;++++++++++++++++xxxxxxx+++;;;;++;;+++++++++++++;++++++++++++++++++++++:.            .;.....::.::::;:;;;:.          
+xxx++xxxxxXXXXxx+++;:::...................  ...:;+xXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxXXXXXXXXXXX;     ..:;+;::::;;;;;++++;..             ..............::;;++++++++++++++++++++++++++++++++++++++++++++++++;;;;;;;;;;;;;;;;;;;;;;++++++++++++++++++xxxxxxxx++::::;;;;;;;;;;;;;;;;;+++;++;;+++++++++++++++++;;:.            ...;:.....:::::::;;:.      
++;:::;;;++++;:......................... ...........:;+xXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxXXXXXXXXXXxxXXXXXXXXXXXXX+.            .;;+++++++:.               . ..............:;;++++++++++++++++++++++++++++++++++++++++++++x+++;;;;;;;;;;;;;;;;;;;;+;+++++++++++++++++x+++:.   ....::::;;;;;;;;;+;;;;;;+++++;++++++++++++++++;;;;:.            ............::::::::.   
xx+xx+;::::.....  .................      ........   ...:;+xXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxXXXXXXXXXXXXXXx+:..       .:;+++++++++:.               .    . ..........::;+++++++++++++++++++++++++++++++++++++++++xxxxxx++;;;;;;;;;;;;;;;;;;++++++++++++++++++++:.           ..::::::;;;;;;;;;;;;+++++++++++++++++++++++++;;;:.             .::.....:..::::::::
xxxx+;:.....    ....................    .............::::;;+xxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxXXXXXXXXXXXXXXXXXx+:::....:;+xxxxxx++++;.                     .    .........::;;;++++++++++++++++++++++++++++++++++++xxxxXXXXxx++;;;;;;;;;;;;;;;;+++++++++++++++++++;:.             ..:::::;;;;;;;;;;;;+++++++++++++++++++++++++;;;::             ............::::
+;;;::..      .................  .          . .................:+xXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxxXXXXXXXXXXXXXXXXXXx;::::;;xxxxxxxx+++++;.                    . .  .... . .......:;;+++++++++++++++++++++++++++++++++xxxXXXXXXXXxx++;;;;;;;;;;;;;++++++++++++++++++++++;:              ...::::;;;;;;;;;+;;++++++++;+++++;++;;+++++++;;;:.             ...    .....
:.....     ...........:...........      ........................:+xXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx+;xxxXXXXXXXXXXXXXXXXXXx;.::;+xxxxxxxx++++++:                                 .........:;+++++++++++++++++++++++++++++++xxxXXXXXXXXXXXXx++;;;;;;;;;;;+++++++++++++++++++++++;;:.              ...:::::;;;;;;++;;++++++++++++++++;;+++++++++;;;:.                ..   
      ...........:.....:::::::...................................:+xXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx++xxxXXXXXXXXXXXXXXXXXXXX+:;+xxxxxxxx+++++++;.                                     ......:;+++++++++++++++++++++++++++++xxxXXXXXXXXXXXXXXXxx++;;;;;;;+++++++++++++++++++++++++++;:.              ....::::;;;;;;+;++;++++++++++++++++++++++++++;;;;.                  
 .  .............:::::;;;++++;.....................:::::::::::::::+xxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx+xxxxXXXXXXXXXXXXX$XXXXXXXX+xxxxxxxxx++++++++.                                       ......:;;+++++++++++++++++++++++++++xxxXXXXXXXXXXXXXXXXXXx++++;+++++++++++++++++++++++++++++;;;;.               ...::::;;;;;;;+;;+++;+++++++++++++++;++++++++;;;:.              
.......::::::.:::;;;+++xx+++;:..........:::::::;;;;;;;;;;;;;;;;;;;+xxxxxxXxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxxxxxXXXXXXXXXXX$XXXXXXXXXXxxxxxxxxxx+++++++:                                            ....::;;;++++++++++++++++++++++xxxXXXXXXXXXXXXXXXXXXXXXxx+++++++++++++++++++++++++++++++++;;;;.               ...:::::;;;;;;;++;++++++;++++++++++++++++++++;;;:.           
...::::;;;;;;;+++++xxxx+++;::.......:::::;;;;+++++++++++++++++++++xxxxxxxxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxXxxxXXXXXXXXX$$XXXXXXXXXXXXXXxxxxxxxx+++++++;.                                             .......::;;++++++++++++++++++xxxXXXXXXXXXXXXXXXXXXXXXXXXxx++++++++++++++++++++++++++++++++;+;;;:.               ...:::;;;;;;;;;;;;+++;++;;+++++++++++++++;;;;;;::.       
::;;;;;;;+++++xxxxx++++;::......:::;;;+++++++++++++++++++++++++++++xxxxxxXXXXXXXXXXXXXXXXXxxxxxxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxxxxxxXxxxXXXXXXXXXXXXXXXXXXXXXXXXXXxxxxxxx++++++++.                                              ..........::;+++++++++++++++xxxxXXXXXXXXXXXXXXXXXXXXXXXXXXXx++++++++++++++++++++++++++++++++++;;;:.               ...::::;;;;;;;;;++;;++;;++;++++++++;;;;;;;;;;;;::.    
;;;+++++++xxxxxx++++;::.......::;;;+++++++++++++++++++++;;;+++++++xxxxxXXXXXXXXxx+;::...        .;+xxXXXXXXXXXXXXXXxXXXXxXxXXxxx+++++++xxxxxxxxxXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxxxxx+++++++:                                                      .....::;;++++++++++++xxxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxx+++++++++++++++++++++++++++++++++;;;;:               ...::::::;;;;;;;++;;;;;;;;;;;+++++;;;;;;;;;;;;;:::.`;
 
 return (
   <div className={`${className} relative`} inert>
      <div className={styles["ascii-base"]}>
        <pre>{asciiArt}</pre>
      </div>
    </div>
  );
};

export default CountBasie;
